/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
#include "main.h"

#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_HEADER_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_HEADER  (GUI_ID_USER + 0x02)
#define ID_BUTTON_GREEN  (GUI_ID_USER + 0x03)
#define ID_BUTTON_LBLUE  (GUI_ID_USER + 0x09)
#define ID_BUTTON_YELLOW  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_PINK  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_BLUE  (GUI_ID_USER + 0x10)
#define ID_BUTTON_CANCEL  (GUI_ID_USER + 0x14)
#define ID_BUTTON_SAVE  (GUI_ID_USER + 0x15)

static GUI_COLOR but_green1, but_green2, but_lblue1, but_lblue2;
static GUI_COLOR but_yellow1, but_yellow2, but_pink1, but_pink2, but_blue1, but_blue2;

static void drawColorButton(GUI_COLOR c1, GUI_COLOR c2)
{
    GUI_DrawGradientRoundedV(0, 0, 74, 48, 2, c1, c2);
    GUI_SetColor(GUI_LIGHTGRAY);
}

static void draw_green_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawColorButton(but_green1, but_green2);
        if (color_scheme == 0)
        {
            GUI_SetPenSize(2);
            GUI_SetColor(GUI_RED);
            GUI_AA_DrawRoundedRect(0, 0, 74, 49, 4);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
static void draw_lightblue_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawColorButton(but_lblue1, but_lblue2);
        if (color_scheme == 1)
        {
            GUI_SetPenSize(2);
            GUI_SetColor(GUI_RED);
            GUI_AA_DrawRoundedRect(0, 0, 74, 49, 4);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
static void draw_yellow_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawColorButton(but_yellow1, but_yellow2);
        if (color_scheme == 2)
        {
            GUI_SetPenSize(2);
            GUI_SetColor(GUI_RED);
            GUI_AA_DrawRoundedRect(0, 0, 74, 49, 4);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
static void draw_pink_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawColorButton(but_pink1, but_pink2);
        if (color_scheme == 3)
        {
            GUI_SetPenSize(2);
            GUI_SetColor(GUI_RED);
            GUI_AA_DrawRoundedRect(0, 0, 74, 49, 4);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
static void draw_blue_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawColorButton(but_blue1, but_blue2);
        if (color_scheme == 4)
        {
            GUI_SetPenSize(2);
            GUI_SetColor(GUI_RED);
            GUI_AA_DrawRoundedRect(0, 0, 74, 49, 4);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "COLORS", ID_TEXT_HEADER, 0, 0, 480, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_GREEN, 20, 120, 75, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_LBLUE, 110, 120, 75, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_YELLOW, 200, 120, 75, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_PINK, 290, 120, 75, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_BLUE, 380, 120, 75, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_CANCEL, 20, 230, 80, 25, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_SAVE, 380, 230, 80, 25, 0, 0x0, 0 },
};

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
        TEXT_SetTextColor(hItem, GUI_WHITE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_GREEN);
        but_green1 = 0x48866c;
        but_green2 = 0x62b29a; //
        WM_SetCallback(hItem, draw_green_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LBLUE);
        but_lblue1 = 0xb7a491;
        but_lblue2 = 0xedb6bd; //
        WM_SetCallback(hItem, draw_lightblue_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_YELLOW);
        but_yellow1 = 0x85b4cb;
        but_yellow2 = 0xa1e6fd; //
        WM_SetCallback(hItem, draw_yellow_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PINK);
        but_pink1 = 0xb794c2;
        but_pink2 = 0xdfc4d8; //
        WM_SetCallback(hItem, draw_pink_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_BLUE);
        but_blue1 = 0x7a5114;
        but_blue2 = 0xc1842d; //
        WM_SetCallback(hItem, draw_blue_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        WM_SetCallback(hItem, cancel_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
        WM_SetCallback(hItem, save_cb);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_GREEN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                color_scheme = 0;
                initColors();
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
                WM_InvalidateWindow(hItem);
                WM_InvalidateWindow(pMsg->hWin);
                break;
            }
            break;
        case ID_BUTTON_LBLUE:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                color_scheme = 1;
                initColors();
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
                WM_InvalidateWindow(hItem);
                WM_InvalidateWindow(pMsg->hWin);
                break;
            }
            break;
        case ID_BUTTON_YELLOW:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                color_scheme = 2;
                initColors();
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
                WM_InvalidateWindow(hItem);
                WM_InvalidateWindow(pMsg->hWin);
                break;
            }
            break;
        case ID_BUTTON_PINK:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                color_scheme = 3;
                initColors();
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
                WM_InvalidateWindow(hItem);
                WM_InvalidateWindow(pMsg->hWin);
                break;
            }
            break;
        case ID_BUTTON_BLUE:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                color_scheme = 4;
                initColors();
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
                WM_InvalidateWindow(hItem);
                WM_InvalidateWindow(pMsg->hWin);
                break;
            }
            break;
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 4;
                break;
            }
            break;
        case ID_BUTTON_SAVE:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 4;
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateColors(void);
WM_HWIN CreateColors(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
