/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "main.h"

#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_HEADER_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_HEADER (GUI_ID_USER + 0x02)
#define ID_BUTTON_HOUR_UP  (GUI_ID_USER + 0x03)
#define ID_BUTTON_HOUR_DN  (GUI_ID_USER + 0x04)
#define ID_BUTTON_MONTH_UP  (GUI_ID_USER + 0x06)
#define ID_BUTTON_MONTH_DN  (GUI_ID_USER + 0x07)
#define ID_BUTTON__MINUTE_UP  (GUI_ID_USER + 0x09)
#define ID_BUTTON_MINUTE_DN  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_DAY_UP  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_DAY_DN  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_AMPM_UP  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_AMPM_DN  (GUI_ID_USER + 0x10)
#define ID_BUTTON__YEAR_UP  (GUI_ID_USER + 0x12)
#define ID_BUTTON_YEAR_DN  (GUI_ID_USER + 0x13)
#define ID_BUTTON_CANCEL  (GUI_ID_USER + 0x14)
#define ID_BUTTON_SAVE  (GUI_ID_USER + 0x15)
#define ID_EDIT_0  (GUI_ID_USER + 0x16)
#define ID_EDIT_MONTH  (GUI_ID_USER + 0x18)
#define ID_EDIT_2  (GUI_ID_USER + 0x19)
#define ID_EDIT_3  (GUI_ID_USER + 0x1A)
#define ID_EDIT_4  (GUI_ID_USER + 0x1B)
#define ID_EDIT_5  (GUI_ID_USER + 0x1C)
#define ID_TEXT_0  (GUI_ID_USER + 0x1D)
#define ID_TEXT_1  (GUI_ID_USER + 0x1E)
#define ID_TEXT_2  (GUI_ID_USER + 0x1F)
#define ID_TEXT_3  (GUI_ID_USER + 0x20)
#define ID_TEXT_4  (GUI_ID_USER + 0x21)
#define ID_TEXT_5  (GUI_ID_USER + 0x22)

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "TIME/DATE", ID_TEXT_HEADER, 0, 0, 480, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_HOUR_UP, 112, 77, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_HOUR_DN, 113, 108, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_MONTH_UP, 113, 151, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_MONTH_DN, 112, 183, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON__MINUTE_UP, 259, 77, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_MINUTE_DN, 259, 109, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_DAY_UP, 259, 157, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_DAY_DN, 260, 188, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_AMPM_UP, 423, 77, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_AMPM_DN, 425, 107, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON__YEAR_UP, 428, 153, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_YEAR_DN, 429, 185, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 20, 230, 80, 24, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SAVE", ID_BUTTON_SAVE, 390, 230, 69, 22, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 40, 80, 64, 46, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "Edit", ID_EDIT_MONTH, 22, 158, 83, 52, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 183, 80, 69, 54, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 191, 160, 62, 52, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 334, 80, 85, 55, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 309, 160, 113, 55, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_0, 43, 57, 59, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 186, 56, 84, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 336, 56, 87, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 26, 140, 80, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 195, 140, 74, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_5, 310, 140, 80, 20, 0, 0x64, 0 },
};

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    // USER START (Optionally insert additional variables)

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetFont(hItem, GUI_FONT_32B_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_HOUR_UP);
        BUTTON_SetText(hItem, "UP1");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_HOUR_DN);
        BUTTON_SetText(hItem, "DN1");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MONTH_UP);
        BUTTON_SetText(hItem, "UP2");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MONTH_DN);
        BUTTON_SetText(hItem, "DN2");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON__MINUTE_UP);
        BUTTON_SetText(hItem, "UP3");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MINUTE_DN);
        BUTTON_SetText(hItem, "DN3");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DAY_UP);
        BUTTON_SetText(hItem, "UP4");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DAY_DN);
        BUTTON_SetText(hItem, "DN4");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_AMPM_UP);
        BUTTON_SetText(hItem, "UP5");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_AMPM_DN);
        BUTTON_SetText(hItem, "DN5");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON__YEAR_UP);
        BUTTON_SetText(hItem, "UP6");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_YEAR_DN);
        BUTTON_SetText(hItem, "DN6");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        BUTTON_SetFont(hItem, GUI_FONT_16B_1);
         BUTTON_SetTextColor(hItem, 0, GUI_MAKE_COLOR(0x00FFFFFF));
       //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
        BUTTON_SetFont(hItem, GUI_FONT_16B_1);
          BUTTON_SetTextColor(hItem, 0, GUI_MAKE_COLOR(0x00FFFFFF));
       //
        // Initialization of 'Edit'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        EDIT_SetText(hItem, "00");
        EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        EDIT_SetFont(hItem, GUI_FONT_32B_1);
        //
        // Initialization of 'Edit'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_MONTH);
        EDIT_SetText(hItem, "JAN");
        EDIT_SetFont(hItem, GUI_FONT_32B_1);
        EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        //
        // Initialization of 'Edit'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
        EDIT_SetText(hItem, "26");
        EDIT_SetFont(hItem, GUI_FONT_32B_1);
        EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        //
        // Initialization of 'Edit'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
        EDIT_SetText(hItem, "28");
        EDIT_SetFont(hItem, GUI_FONT_32B_1);
        EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        //
        // Initialization of 'Edit'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
        EDIT_SetText(hItem, "AM");
        EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        EDIT_SetFont(hItem, GUI_FONT_32B_1);
        //
        // Initialization of 'Edit'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
        EDIT_SetText(hItem, "2017");
        EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        EDIT_SetFont(hItem, GUI_FONT_32B_1);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "Hour");
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Minute");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "AM/PM");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "Month");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Day");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Year");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        // USER START (Optionally insert additional code for further widget initialization)
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_HOUR_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_HOUR_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_MONTH_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_MONTH_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON__MINUTE_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_MINUTE_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
             }
            break;
        case ID_BUTTON_DAY_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_DAY_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_AMPM_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_AMPM_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
             }
            break;
        case ID_BUTTON__YEAR_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_YEAR_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
             }
            break;
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 4;
                break;
            }
            break;
        case ID_BUTTON_SAVE:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 4;
                break;
           }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateDateTime(void);
WM_HWIN CreateDateTime(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}


/*************************** End of file ****************************/
