/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "main.h"

#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_HEADER_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_HEADER (GUI_ID_USER + 0x02)
#define ID_BUTTON_HOUR_UP  (GUI_ID_USER + 0x03)
#define ID_BUTTON_HOUR_DN  (GUI_ID_USER + 0x04)
#define ID_BUTTON_MONTH_UP  (GUI_ID_USER + 0x06)
#define ID_BUTTON_MONTH_DN  (GUI_ID_USER + 0x07)
#define ID_BUTTON_MINUTE_UP  (GUI_ID_USER + 0x09)
#define ID_BUTTON_MINUTE_DN  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_DAY_UP  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_DAY_DN  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_AMPM_UP  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_AMPM_DN  (GUI_ID_USER + 0x10)
#define ID_BUTTON__YEAR_UP  (GUI_ID_USER + 0x12)
#define ID_BUTTON_YEAR_DN  (GUI_ID_USER + 0x13)
#define ID_BUTTON_CANCEL  (GUI_ID_USER + 0x14)
#define ID_BUTTON_SAVE  (GUI_ID_USER + 0x15)
#define ID_EDIT_HOUR  (GUI_ID_USER + 0x16)
#define ID_EDIT_MONTH  (GUI_ID_USER + 0x18)
#define ID_EDIT_MINUTE  (GUI_ID_USER + 0x19)
#define ID_EDIT_DAY  (GUI_ID_USER + 0x1A)
#define ID_EDIT_AMPM  (GUI_ID_USER + 0x1B)
#define ID_EDIT_YEAR  (GUI_ID_USER + 0x1C)
#define ID_TEXT_0  (GUI_ID_USER + 0x1D)
#define ID_TEXT_1  (GUI_ID_USER + 0x1E)
#define ID_TEXT_2  (GUI_ID_USER + 0x1F)
#define ID_TEXT_3  (GUI_ID_USER + 0x20)
#define ID_TEXT_4  (GUI_ID_USER + 0x21)
#define ID_TEXT_5  (GUI_ID_USER + 0x22)

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "TIME/DATE", ID_TEXT_HEADER, 0, 0, 480, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_HOUR_UP, 110, 74, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_HOUR_DN, 110, 104, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_MONTH_UP, 110, 154, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_MONTH_DN, 110, 183, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_MINUTE_UP, 258, 75, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_MINUTE_DN, 258, 104, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_DAY_UP, 258, 154, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_DAY_DN, 258, 183, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_AMPM_UP, 423, 75, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_AMPM_DN, 423, 104, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON__YEAR_UP, 423, 154, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_YEAR_DN, 423, 183, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 20, 230, 80, 25, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SAVE", ID_BUTTON_SAVE, 380, 230, 80, 25, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Edit", ID_EDIT_HOUR, 40, 80, 70, 55, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Edit", ID_EDIT_MONTH, 26, 160, 83, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Edit", ID_EDIT_MINUTE, 190, 80, 70, 55, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Edit", ID_EDIT_DAY, 191, 160, 70, 55, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Edit", ID_EDIT_AMPM, 355, 80, 70, 55, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Edit", ID_EDIT_YEAR, 309, 160, 116, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_0, 43, 58, 59, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 186, 58, 84, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 355, 58, 87, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 26, 140, 80, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 195, 140, 74, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_5, 310, 140, 80, 20, 0, 0x64, 0 },
};
extern void small_up_button(WM_MESSAGE *);
extern void small_dn_button(WM_MESSAGE *);

static char *Months[] = {"JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"};
static int days[12] = {30,28,30,30,30,30,30,30,30,30,30,30};


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    char buf[10];

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetFont(hItem, &GUI_Font32B_ASCII);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_HOUR_UP);
        WM_SetCallback(hItem, small_up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_HOUR_DN);
        WM_SetCallback(hItem, small_dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MONTH_UP);
        WM_SetCallback(hItem, small_up_button);;
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MONTH_DN);
        WM_SetCallback(hItem, small_dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MINUTE_UP);
        WM_SetCallback(hItem, small_up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MINUTE_DN);
        WM_SetCallback(hItem, small_dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DAY_UP);
        WM_SetCallback(hItem, small_up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DAY_DN);
        WM_SetCallback(hItem, small_dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_AMPM_UP);
        WM_SetCallback(hItem, small_up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_AMPM_DN);
        WM_SetCallback(hItem, small_dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON__YEAR_UP);
        WM_SetCallback(hItem, small_up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_YEAR_DN);
        WM_SetCallback(hItem, small_dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        WM_SetCallback(hItem, buttonOn16_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
        WM_SetCallback(hItem, buttonOn16_cb);
        //
        sprintf(buf, "%d", current_hour);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_HOUR);
        BUTTON_SetText(hItem, buf);
        WM_SetCallback(hItem, edit_text_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_MONTH);
        BUTTON_SetText(hItem, Months[current_month]);
        WM_SetCallback(hItem, edit_text_cb);
        //
        sprintf(buf, "%d", current_minute);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_MINUTE);
        BUTTON_SetText(hItem, buf);
        WM_SetCallback(hItem, edit_text_cb);
        //
        sprintf(buf, "%d", current_day);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DAY);
        BUTTON_SetText(hItem, buf);
        WM_SetCallback(hItem, edit_text_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AMPM);
        BUTTON_SetText(hItem, current_ampm ? "AM" : "PM");
        WM_SetCallback(hItem, edit_text_cb);
        //
        sprintf(buf, "%d", current_year);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_YEAR);
        BUTTON_SetText(hItem, buf);
        WM_SetCallback(hItem, edit_text_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "Hour");
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Minute");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "AM/PM");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "Month");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Day");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Year");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_HOUR_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_HOUR_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_MONTH_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_MONTH_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_MINUTE_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_MINUTE_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_DAY_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_DAY_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_AMPM_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_AMPM_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON__YEAR_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_YEAR_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                state = 4;
                break;
            }
            break;
        case ID_BUTTON_SAVE:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                state = 4;
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateDateTime(void);
WM_HWIN CreateDateTime(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}


/*************************** End of file ****************************/
