/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "main.h"

#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_HEADER_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_CANCEL (GUI_ID_USER + 0x02)
#define ID_BUTTON_EDIT (GUI_ID_USER + 0x03)
#define ID_TEXT_WAKE (GUI_ID_USER + 0x04)
#define ID_TEXT_START_TIME (GUI_ID_USER + 0x05)
#define ID_TEXT_END_TIME (GUI_ID_USER + 0x06)
#define ID_TEXT_3 (GUI_ID_USER + 0x07)
#define ID_TEXT_MONDAY (GUI_ID_USER + 0x08)
#define ID_TEXT_TUESDAY (GUI_ID_USER + 0x09)
#define ID_TEXT_WEDNESDAY (GUI_ID_USER + 0x0A)
#define ID_TEXT_THURSDAY (GUI_ID_USER + 0x0B)
#define ID_TEXT_FRIDAY (GUI_ID_USER + 0x0C)
#define ID_TEXT_SATURDAY (GUI_ID_USER + 0x0D)
#define ID_TEXT_SUNDAY (GUI_ID_USER + 0x0E)

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 20, 220, 80, 28, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "EDIT", ID_BUTTON_EDIT, 378, 220, 76, 28, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "WAKE", ID_TEXT_WAKE, 31, 60, 83, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_START_TIME, 144, 60, 80, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_END_TIME, 251, 60, 81, 22, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "temp", ID_TEXT_3, 363, 60, 80, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "M", ID_TEXT_MONDAY, 28, 0, 32, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "T", ID_TEXT_TUESDAY, 80, 0, 32, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "W", ID_TEXT_WEDNESDAY, 133, 0, 50, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TH", ID_TEXT_THURSDAY, 195, 0, 59, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "F", ID_TEXT_FRIDAY, 269, 0, 42, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "S", ID_TEXT_SATURDAY, 329, 0, 47, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "SU", ID_TEXT_SUNDAY, 390, 0, 71, 50, 0, 0x64, 0 },
};

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        BUTTON_SetFont(hItem, &GUI_FontRounded16);
        BUTTON_SetTextColor(hItem, 0, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT);
        BUTTON_SetFont(hItem, &GUI_FontRounded16);
        BUTTON_SetTextColor(hItem, 0, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WAKE);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_START_TIME);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "6:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_END_TIME);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "8:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "78");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MONDAY);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32B_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TUESDAY);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WEDNESDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_THURSDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FRIDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SATURDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SUNDAY);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 30;
                break;
            }
            break;
        case ID_BUTTON_EDIT:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateEachDay(void);
WM_HWIN CreateEachDay(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
