/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "main.h"

#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_HEADER_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_CANCEL (GUI_ID_USER + 0x02)
#define ID_BUTTON_EDIT (GUI_ID_USER + 0x03)
#define ID_TEXT_WAKE (GUI_ID_USER + 0x04)
#define ID_TEXT_WAKE_TIME (GUI_ID_USER + 0x05)
#define ID_TEXT_WAKE_TEMP (GUI_ID_USER + 0x07)

#define ID_TEXT_LEAVE (GUI_ID_USER + 0x08)
#define ID_TEXT_LEAVE_TIME (GUI_ID_USER + 0x09)
#define ID_TEXT_LEAVE_TEMP (GUI_ID_USER + 0x0A)

#define ID_TEXT_RETURN (GUI_ID_USER + 0x0B)
#define ID_TEXT_RETURN_TIME (GUI_ID_USER + 0x0C)
#define ID_TEXT_RETURN_TEMP (GUI_ID_USER + 0x0D)

#define ID_TEXT_SLEEP (GUI_ID_USER + 0x0E)
#define ID_TEXT_SLEEP_TIME (GUI_ID_USER + 0x0F)
#define ID_TEXT_SLEEP_TEMP (GUI_ID_USER + 0xA0)

#define ID_TEXT_MONDAY (GUI_ID_USER + 0xA1)
#define ID_TEXT_TUESDAY (GUI_ID_USER + 0xA2)
#define ID_TEXT_WEDNESDAY (GUI_ID_USER + 0xA3)
#define ID_TEXT_THURSDAY (GUI_ID_USER + 0xA4)
#define ID_TEXT_FRIDAY (GUI_ID_USER + 0xA5)
#define ID_TEXT_SATURDAY (GUI_ID_USER + 0xA6)
#define ID_TEXT_SUNDAY (GUI_ID_USER + 0xA7)

static int days[] = {
        ID_TEXT_MONDAY,ID_TEXT_TUESDAY,ID_TEXT_WEDNESDAY,
        ID_TEXT_THURSDAY,ID_TEXT_FRIDAY, ID_TEXT_SATURDAY, ID_TEXT_SUNDAY
        };

static void resetFonts(WM_HWIN win, int id) {
     WM_HWIN txt;
     int i;
     for (i=0;i<7;i++) {
        txt = WM_GetDialogItem(win, days[i]);
        TEXT_SetFont(txt, GUI_FONT_32_1);
    }
    txt = WM_GetDialogItem(win, id);
    TEXT_SetFont(txt, GUI_FONT_32B_1);
}

static int selected_day;
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },

    { TEXT_CreateIndirect, "M", ID_TEXT_MONDAY, 28, 0, 32, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "T", ID_TEXT_TUESDAY, 80, 0, 32, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "W", ID_TEXT_WEDNESDAY, 133, 0, 50, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TH", ID_TEXT_THURSDAY, 195, 0, 59, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "F", ID_TEXT_FRIDAY, 269, 0, 42, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "S", ID_TEXT_SATURDAY, 329, 0, 47, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "SU", ID_TEXT_SUNDAY, 390, 0, 71, 50, 0, 0x64, 0 },

    { TEXT_CreateIndirect, "WAKE", ID_TEXT_WAKE, 31, 65, 83, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TIME", ID_TEXT_WAKE_TIME, 144, 65, 200, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TEMP", ID_TEXT_WAKE_TEMP, 363, 65, 80, 20, 0, 0x64, 0 },

    { TEXT_CreateIndirect, "LEAVE", ID_TEXT_LEAVE, 31, 105, 83, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TIME", ID_TEXT_LEAVE_TIME, 144, 105, 200, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TEMP", ID_TEXT_LEAVE_TEMP, 363, 105, 80, 20, 0, 0x64, 0 },

    { TEXT_CreateIndirect, "RETURN", ID_TEXT_RETURN, 31, 145, 83, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TIME", ID_TEXT_RETURN_TIME, 144, 145, 200, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TEMP", ID_TEXT_RETURN_TEMP, 363, 145, 80, 20, 0, 0x64, 0 },

    { TEXT_CreateIndirect, "SLEEP", ID_TEXT_SLEEP, 31, 185, 83, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TIME", ID_TEXT_SLEEP_TIME, 144, 185, 200, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TEMP", ID_TEXT_SLEEP_TEMP, 363, 185, 80, 20, 0, 0x64, 0 },

    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 20, 230, 80, 28, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "EDIT", ID_BUTTON_EDIT, 375, 230, 80, 28, 0, 0x0, 0 },

};

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        GUI_SetColor(0xcecece);
        GUI_DrawHLine(92, 0, 479);
        GUI_DrawHLine(132, 0, 479);
        GUI_DrawHLine(172, 0, 479);
        break;
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MONDAY);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32B_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TUESDAY);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WEDNESDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_THURSDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FRIDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SATURDAY);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SUNDAY);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WAKE);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WAKE_TIME);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetText(hItem, "6:00 am - 8:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WAKE_TEMP);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "78");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEAVE);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEAVE_TIME);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetText(hItem, "6:00 am - 8:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEAVE_TEMP);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "78");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RETURN);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RETURN_TIME);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetText(hItem, "6:00 am - 8:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RETURN_TEMP);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "78");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SLEEP);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SLEEP_TIME);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetText(hItem, "6:00 am - 8:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SLEEP_TEMP);
        TEXT_SetFont(hItem, &FontBig20B);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "78");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        WM_SetCallback(hItem, buttonOn16_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT);
        WM_SetCallback(hItem, buttonOn16_cb);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_TEXT_MONDAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                selected_day = 0;
                resetFonts(pMsg->hWin, ID_TEXT_MONDAY);
                break;
            }
            break;
        case ID_TEXT_TUESDAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                 selected_day = 1;
               resetFonts(pMsg->hWin, ID_TEXT_TUESDAY);
                break;
            }
            break;
        case ID_TEXT_WEDNESDAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                 selected_day = 2;
               resetFonts(pMsg->hWin, ID_TEXT_WEDNESDAY);
                break;
            }
            break;
        case ID_TEXT_THURSDAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                  selected_day = 3;
              resetFonts(pMsg->hWin, ID_TEXT_THURSDAY);
                break;
            }
            break;
        case ID_TEXT_FRIDAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                    selected_day = 4;
            resetFonts(pMsg->hWin, ID_TEXT_FRIDAY);
                break;
            }
            break;
        case ID_TEXT_SATURDAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                       selected_day = 5;
         resetFonts(pMsg->hWin, ID_TEXT_SATURDAY);
                break;
            }
            break;
        case ID_TEXT_SUNDAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                       selected_day =6;
         resetFonts(pMsg->hWin, ID_TEXT_SUNDAY);
                break;
            }
            break;
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                state = 13;
                break;
            }
            break;
        case ID_BUTTON_EDIT:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateEachDay(void);
WM_HWIN CreateEachDay(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
