/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "main.h"

#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_HEADER_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_HEADER  (GUI_ID_USER + 0x02)
#define ID_TEXT_1  (GUI_ID_USER + 0x03)
#define ID_TEXT_2  (GUI_ID_USER + 0x04)
#define ID_TEXT_3  (GUI_ID_USER + 0x05)
#define ID_TEXT_4  (GUI_ID_USER + 0x06)
#define ID_BUTTON_CUSTOMER  (GUI_ID_USER + 0x07)
#define ID_BUTTON_ZIP  (GUI_ID_USER + 0x08)
#define ID_BUTTON_MAC  (GUI_ID_USER + 0x09)
#define ID_BUTTON_CRC  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_CANCEL  (GUI_ID_USER + 0x0B)
#define ID_BUTTON_SAVE  (GUI_ID_USER + 0x0C)

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "PROFILE", ID_TEXT_HEADER, 0, 0, 480, 50, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 94, 168, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 129, 168, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 0, 163, 168, 20, 0, 0x64, 0 },
//    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 0, 180, 178, 20, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Frank", ID_BUTTON_CUSTOMER, 176, 90, 230, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "32807", ID_BUTTON_ZIP, 176, 125, 230, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "", ID_BUTTON_MAC, 176, 160, 230, 30, 0, 0x0, 0 },
//    { BUTTON_CreateIndirect, "12334", ID_BUTTON_CRC, 186, 175, 230, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 20, 230, 75, 25, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SAVE", ID_BUTTON_SAVE, 390, 230, 75, 25, 0, 0x0, 0 },
};

char customer_text[30], mac_text[30], zip_text[12], crc_text[10];
void customer_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawProfileButton(customer_text, 220, 30, color_scheme);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
void mac_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawProfileButton(mac_text, 220, 30, color_scheme);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
void zip_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawProfileButton(zip_text, 220, 30, color_scheme);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
void crc_cb(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawProfileButton(crc_text, 220, 30, color_scheme);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Name:");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00008080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "Zip Code:");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00008080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetText(hItem, "MAC Address:");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00008080));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        WM_SetCallback(hItem, crc_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ZIP);
        WM_SetCallback(hItem, zip_cb);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CUSTOMER);
        WM_SetCallback(hItem, customer_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MAC);
        WM_SetCallback(hItem, mac_cb);
        //
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CRC);
//        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
//        BUTTON_SetTextColor(hItem, 0, GUI_MAKE_COLOR(0x00FFFFFF));
//        BUTTON_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        WM_SetCallback(hItem, cancel_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
        WM_SetCallback(hItem, save_cb);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_CUSTOMER:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 8;
                break;
            }
            break;
        case ID_BUTTON_ZIP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 2;
                break;
            }
            break;
        case ID_BUTTON_MAC:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 8;
                break;
            }
            break;
        case ID_BUTTON_CRC:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 8;
                break;
            }
            break;
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 4;
                break;
            }
            break;
        case ID_BUTTON_SAVE:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 4;
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateProfile(void);
WM_HWIN CreateProfile(void)
{
    WM_HWIN hWin;
    strcpy(crc_text, "1234");
    strcpy(zip_text, "32807-1234");
    strcpy(customer_text, "BLOWME");
        strcpy(mac_text, "00:11:22:44:55:66");

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
