/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "ranger.h"

#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_HEADER_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_HEADER (GUI_ID_USER + 0x02)
#define ID_BUTTON_0  (GUI_ID_USER + 0x03)
#define ID_BUTTON_1  (GUI_ID_USER + 0x04)
#define ID_BUTTON_2  (GUI_ID_USER + 0x07)
#define ID_BUTTON_3  (GUI_ID_USER + 0x09)
#define ID_BUTTON_4  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_5  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_6  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_7  (GUI_ID_USER + 0x10)
#define ID_BUTTON_CANCEL  (GUI_ID_USER + 0x14)
#define ID_BUTTON_SAVE  (GUI_ID_USER + 0x15)
#define ID_EDIT_0  (GUI_ID_USER + 0x16)
#define ID_EDIT_1  (GUI_ID_USER + 0x19)
#define ID_EDIT_2  (GUI_ID_USER + 0x1A)
#define ID_EDIT_3  (GUI_ID_USER + 0x1C)

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "SCREEN LOCK", ID_TEXT_HEADER, 0, 0, 480, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 105, 64, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 105, 182, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 184, 64, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 184, 182, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 264, 64, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 264, 182, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 344, 64, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 344, 182, 50, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 20, 230, BUT_WIDTH, BUT_HEIGHT, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SAVE", ID_BUTTON_SAVE, 350, 230, BUT_WIDTH, BUT_HEIGHT, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Edit", ID_EDIT_0, 94, 110, 70, 70, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Edit", ID_EDIT_1, 174, 110, 70, 70, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Edit", ID_EDIT_2, 254, 110, 70, 70, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Edit", ID_EDIT_3, 334, 110, 70, 70, 0, 0x64, 0 },
};

static int dig1, dig2, dig3, dig4;
extern GUI_CONST_STORAGE GUI_BITMAP bmup_s_lg;
extern GUI_CONST_STORAGE GUI_BITMAP bmdn_s_lg;

static void up_button(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        if (BUTTON_IsPressed(pMsg->hWin))
        {
            GUI_DrawBitmap(&bmup_s_lg, 0, 0);
        }
        else
        {
            GUI_DrawBitmap(&bmup_s_lg, 0, 0);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void dn_button(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        if (BUTTON_IsPressed(pMsg->hWin))
        {
            GUI_DrawBitmap(&bmdn_s_lg, 0, 0);
        }
        else
        {
            GUI_DrawBitmap(&bmdn_s_lg, 0, 0);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void text_box_cb(WM_MESSAGE * pMsg)
{
    char buf[50];
    GUI_RECT rt;
    WM_GetClientRect(&rt);
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        TEXT_GetText(pMsg->hWin, buf, 10);
        GUI_DrawGradientRoundedV(0, 0, rt.x1, rt.y1, 4, color_map[2].stop, color_map[2].start);
        GUI_SetColor(0x808080);
        GUI_SetTextMode(GUI_TEXTMODE_TRANS);
        GUI_SetFont(Tahoma88B);
        rt.x0+=2;
        rt.y0-=4;
        GUI_DispStringInRect(buf, &rt, GUI_TA_HCENTER | GUI_TA_VCENTER);
        break;
    default:
        TEXT_Callback(pMsg);
        break;
    }
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    char buf[2];

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        GUI_DrawGradientV(0, 0, 480, 50, color_map[0].stop, color_map[0].start);
        GUI_DrawBitmap(&bmwatermark,45,52);
        break;
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetFont(hItem, GUI_FONT_32B_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        TEXT_SetText(hItem, LANG("SCREEN LOCK"));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        WM_SetCallback(hItem, up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        WM_SetCallback(hItem, dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        WM_SetCallback(hItem, up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        WM_SetCallback(hItem, dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        WM_SetCallback(hItem, up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
        WM_SetCallback(hItem, dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
        WM_SetCallback(hItem, up_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
        WM_SetCallback(hItem, dn_button);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        WM_SetCallback(hItem, buttonOn_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
        WM_SetCallback(hItem, buttonOn_cb);
        //
        dig1 = lockCode[0] - 48;
        dig2 = lockCode[1] - 48;
        dig3 = lockCode[2] - 48;
        dig4 = lockCode[3] - 48;
        sprintf(buf, "%d", dig1);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        TEXT_SetText(hItem, buf);
        WM_SetCallback(hItem, text_box_cb);
        //
        sprintf(buf, "%d", dig2);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
        TEXT_SetText(hItem, buf);
        WM_SetCallback(hItem, text_box_cb);
        //
        sprintf(buf, "%d", dig3);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
        TEXT_SetText(hItem, buf);
        WM_SetCallback(hItem, text_box_cb);
        //
        sprintf(buf, "%d", dig4);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
        TEXT_SetText(hItem, buf);
        WM_SetCallback(hItem, text_box_cb);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_0:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig1++;
                if (dig1 == 10) dig1 = 0;
                sprintf(buf,"%d", dig1);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_1:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig1--;
                if (dig1 == -1) dig1 = 9;
                sprintf(buf,"%d", dig1);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_2:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig2++;
                if (dig2 == 10) dig2 = 0;
                sprintf(buf,"%d", dig2);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_3:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig2--;
                if (dig2 == -1) dig2 = 9;
                sprintf(buf,"%d", dig2);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_4:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig3++;
                if (dig3 == 10) dig3 = 0;
                sprintf(buf,"%d", dig3);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_5:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig3--;
                if (dig3 == -1) dig3 = 9;
                sprintf(buf,"%d", dig3);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_6:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig4++;
                if (dig4 == 10) dig4 = 0;
                sprintf(buf,"%d", dig4);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_7:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                dig4--;
                if (dig4 == -1) dig4 = 9;
                sprintf(buf,"%d", dig4);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
                TEXT_SetText(hItem, buf);
                break;
            }
            break;
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                GUI_Delay(100);
                WM_HideWindow(screenLockoutWin);
                screenState = SETTINGSWIN;
                break;
            }
            break;
        case ID_BUTTON_SAVE:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                lockCode[0] = dig1 + 48;
                lockCode[1] = dig2 + 48;
                lockCode[2] = dig3 + 48;
                lockCode[3] = dig4 + 48;
                lockCode[4] = '\0';

                GUI_Delay(100);
                WM_HideWindow(screenLockoutWin);
                screenState = SETTINGSWIN;
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateScreenLockout(void);
WM_HWIN CreateScreenLockout(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    WM_HideWindow(hWin);
    return hWin;
}

/*************************** End of file ****************************/
