/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "main.h"

#define ID_WINDOW_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_SET_SCHEDULE (GUI_ID_USER + 0x05)
#define ID_BUTTON_EDIT (GUI_ID_USER + 0x06)
#define ID_HEADER_0 (GUI_ID_USER + 0x07)
#define ID_TEXT_HEADER (GUI_ID_USER + 0x08)
#define ID_BUTTON_ALL_DAYS (GUI_ID_USER + 0x09)
#define ID_BUTTON_WEEKEND (GUI_ID_USER + 0x0A)
#define ID_BUTTON_EACH_DAY (GUI_ID_USER + 0x0B)
#define ID_BUTTON_VACATION (GUI_ID_USER + 0x0C)
#define ID_BUTTON_HELP (GUI_ID_USER + 0x0D)
#define ID_BUTTON_RETURN (GUI_ID_USER + 0x0E)

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SET SCHEDULE", ID_BUTTON_SET_SCHEDULE, 20, 230, 143, 28, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "EDIT", ID_BUTTON_EDIT, 375, 230, 80, 28, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect,   "SETTINGS: SCHEDULE", ID_TEXT_HEADER, 0, 0, 480, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "All Days", ID_BUTTON_ALL_DAYS, 20, 90, 200, 42, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Weekday/Weekend", ID_BUTTON_WEEKEND, 20, 150, 200, 42, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Each Day", ID_BUTTON_EACH_DAY, 255, 90, 200, 42, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Vacation", ID_BUTTON_VACATION, 255, 150, 200, 42, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "HELP", ID_BUTTON_HELP, 204, 230, 80, 28, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "return", ID_BUTTON_RETURN, 20, 0, 50, 50, 0, 0x0, 0 },
};
static char schedule[20];
static int vacation_border, allDays_border, weekend_border, eachDay_border;

static void schedButton(WM_MESSAGE * pMsg, char *nm, int bor)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        if (BUTTON_IsPressed(pMsg->hWin)) {
            drawButton22(nm, 200, 42, bor, 1);
        } else {
            drawButton22(nm, 200, 42, bor, 0);
        }
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
static void vacation_cb(WM_MESSAGE * pMsg)
{
    schedButton(pMsg, "Vacation", vacation_border);
}

static void allDays_cb(WM_MESSAGE * pMsg)
{
    schedButton(pMsg, "All Days", allDays_border);
}

static void eachDay_cb(WM_MESSAGE * pMsg)
{
    schedButton(pMsg, "Each Day", eachDay_border);
}

static void weekend_cb(WM_MESSAGE * pMsg)
{
    schedButton(pMsg, "Weekday/Weekend", weekend_border);
}


static void invalidateButtons(WM_HWIN hWin)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, ID_BUTTON_ALL_DAYS);
    WM_InvalidateWindow(hItem);
    WM_SetCallback(hItem, allDays_cb);

    hItem = WM_GetDialogItem(hWin, ID_BUTTON_WEEKEND);
    WM_InvalidateWindow(hItem);
    WM_SetCallback(hItem, weekend_cb);

    hItem = WM_GetDialogItem(hWin, ID_BUTTON_EACH_DAY);
    WM_InvalidateWindow(hItem);
    WM_SetCallback(hItem, eachDay_cb);

    hItem = WM_GetDialogItem(hWin, ID_BUTTON_VACATION);
    WM_InvalidateWindow(hItem);
    WM_SetCallback(hItem, vacation_cb);

}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    const void * pData;
    U32          FileSize;
    GUI_RECT rect;
    rect.x0 = 0;
    rect.y0 = 60;
    rect.x1 = 480;
    rect.y1 = 200;

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        GUI_DrawBitmap(&bmwatermark, 0,50);
        //WM_InvalidateArea(&rect);
        break;
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetFont(hItem, GUI_FONT_32B_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
        WM_SetCallback(hItem, return_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ALL_DAYS);
        WM_SetCallback(hItem, allDays_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_WEEKEND);
        WM_SetCallback(hItem, weekend_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EACH_DAY);
        WM_SetCallback(hItem, eachDay_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_VACATION);
        WM_SetCallback(hItem, vacation_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_HELP);
        WM_SetCallback(hItem, buttonOn16_cb);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SET_SCHEDULE);
        WM_SetCallback(hItem, buttonOn16_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT);
        WM_SetCallback(hItem, buttonOn16_cb);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        GUI_RECT rect;
        rect.x0 = 0;
        rect.y0 = 60;
        rect.x1 = 480;
        rect.y1 = 200;
        switch(Id)
        {
        case ID_BUTTON_RETURN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state=4;
            }
            break;
        case ID_BUTTON_SET_SCHEDULE:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                strcpy(selectedSchedule, schedule);
                break;
            }
            break;
        case ID_BUTTON_EDIT:
            switch(NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                if (vacation_border)
                {
                    CreateEditSchedule("vacation");
                }
                else if (weekend_border)
                {
                    CreateEditSchedule("weekend");
                }
                else if (eachDay_border)
                {
                    CreateEachDay();
                }
                else
                {
                    CreateEditSchedule("all days");
                }
                GUI_Delay(100);
                break;
            }
            break;
        case ID_BUTTON_ALL_DAYS:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ALL_DAYS);
                WM_SetCallback(hItem, buttonPush22_cb);
                break;
            case WM_NOTIFICATION_RELEASED:
                invalidateButtons(pMsg->hWin);
                strcpy(schedule, "All Days");
                vacation_border = 0;
                allDays_border = 1;
                eachDay_border = 0;
                weekend_border = 0;
                break;
            }
            break;
        case ID_BUTTON_WEEKEND:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_WEEKEND);
                WM_SetCallback(hItem, buttonPush22_cb);
                break;
            case WM_NOTIFICATION_RELEASED:
                 invalidateButtons(pMsg->hWin);
               strcpy(schedule, "Weekend");
                vacation_border = 0;
                allDays_border = 0;
                eachDay_border = 0;
                weekend_border = 1;
                break;
            }
            break;
        case ID_BUTTON_EACH_DAY:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EACH_DAY);
                WM_SetCallback(hItem, buttonPush22_cb);
                break;
            case WM_NOTIFICATION_RELEASED:
                invalidateButtons(pMsg->hWin);
                strcpy(schedule, "Each Day");
                vacation_border = 0;
                allDays_border = 0;
                eachDay_border = 1;
                weekend_border = 0;
                break;
            }
            break;
        case ID_BUTTON_VACATION:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_VACATION);
                WM_SetCallback(hItem, buttonPush22_cb);
                break;
            case WM_NOTIFICATION_RELEASED:
                invalidateButtons(pMsg->hWin);
                strcpy(schedule, "Vacation");
                vacation_border = 1;
                allDays_border = 0;
                eachDay_border = 0;
                weekend_border = 0;
                break;
            }
            break;
        case ID_BUTTON_HELP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_HELP);
                WM_SetCallback(hItem, buttonPush16_cb);
                break;
            case WM_NOTIFICATION_RELEASED:
                CreateScheduleHelp();
                GUI_Delay(100);
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateSettingsSchedule(void);
WM_HWIN CreateSettingsSchedule(void)
{
    WM_HWIN hWin;

    vacation_border = 0;
    allDays_border = 0;
    eachDay_border = 0;
    weekend_border = 0;

    if (strcmp(selectedSchedule, "all days") == 0)
    {
        allDays_border = 1;

    }
    else if (strcmp(selectedSchedule, "each day") == 0)
    {
        eachDay_border = 1;

    }
    else if (strcmp(selectedSchedule, "weekend") == 0)
    {
        weekend_border = 1;

    }
    else
    {
        vacation_border = 1;

    }

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
