/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "main.h"

#define ID_WINDOW_0 (GUI_ID_USER + 0x02)
#define ID_HEADER_0 (GUI_ID_USER + 0x07)
#define ID_TEXT_HEADER (GUI_ID_USER + 0x08)
#define ID_BUTTON_CANCEL (GUI_ID_USER + 0x11)
#define ID_BUTTON_SAVE (GUI_ID_USER + 0x15)
#define ID_TEXT_TITLE (GUI_ID_USER + 0x25)
#define ID_BUTTON_PERIOD (GUI_ID_USER + 0x26)
#define ID_BUTTON_START (GUI_ID_USER + 0x27)
#define ID_BUTTON_STOP (GUI_ID_USER + 0x28)
#define ID_BUTTON_TEMPURATURE (GUI_ID_USER + 0x29)
#define ID_TEXT_WAKE (GUI_ID_USER + 0x2A)
#define ID_TEXT_START_TIME (GUI_ID_USER + 0x2B)
#define ID_TEXT_STOP_TIME (GUI_ID_USER + 0x2C)
#define ID_TEXT_TEMP_VAR (GUI_ID_USER + 0x2D)
#define ID_BUTTON_UP (GUI_ID_USER + 0x2E)
#define ID_BUTTON_DN (GUI_ID_USER + 0x2F)

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "EDIT SCHEDULE", ID_TEXT_HEADER, 0, 0, 252, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 20, 230, 80, 25, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SAVE", ID_BUTTON_SAVE, 378, 230, 80, 25, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "VACATION", ID_TEXT_TITLE, 280, 0, 189, 50, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "PERIOD", ID_BUTTON_PERIOD, 25, 90, 90, 26, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "START", ID_BUTTON_START, 136, 90, 90, 26, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "STOP", ID_BUTTON_STOP, 245, 90, 90, 26, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_TEMPURATURE, 354, 90, 90, 26, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "WAKE", ID_TEXT_WAKE, 31, 60, 83, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_START_TIME, 144, 60, 80, 23, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_STOP_TIME, 251, 62, 81, 22, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "TEMP", ID_TEXT_TEMP_VAR, 363, 63, 80, 20, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "", ID_BUTTON_UP, 45, 118, 48, 48, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "", ID_BUTTON_DN, 45, 165, 48, 48, 0, 0x0, 0 },
};

static void period_button_off(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("PERIOD", 90, 26, 0);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
static void start_button_off(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("START",90, 26, 0);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void stop_button_off(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("STOP", 90, 26, 0);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void temp_button_off(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("TEMP", 90, 26, 0);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void period_button_on(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("PERIOD",90, 26, 1);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void start_button_on(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("START",90, 26, 1);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void stop_button_on(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("STOP", 90, 26, 1);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}

static void temp_button_on(WM_MESSAGE * pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        drawButton16("TEMP", 90, 26,1);
        break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}
static WM_HWIN period_button, start_button, stop_button, temp_button;
static WM_HWIN upButton, dnButton, weekdayButton;

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TITLE);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32B_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        WM_SetCallback(hItem, buttonOn16_cb);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
        WM_SetCallback(hItem, buttonOn16_cb);
        //
        period_button = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PERIOD);
        WM_SetCallback(period_button, period_button_on);
        //
        start_button = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_START);
        WM_SetCallback(start_button, start_button_off);
        //
        stop_button = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_STOP);
        WM_SetCallback(stop_button, stop_button_off);
        //
        temp_button = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_TEMPURATURE);
        WM_SetCallback(temp_button, temp_button_off);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WAKE);
        TEXT_SetFont(hItem, GUI_FONT_20B_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_START_TIME);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_20B_1);
        TEXT_SetText(hItem, "6:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_STOP_TIME);
        TEXT_SetFont(hItem, GUI_FONT_20B_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "8:00 am");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TEMP_VAR);
        TEXT_SetFont(hItem, GUI_FONT_20B_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, "78");
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B4B4B4));
        //
        upButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_UP);
        WM_SetCallback(upButton, big_up_button);
        //
        dnButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DN);
        WM_SetCallback(dnButton, big_dn_button);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_CANCEL:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 13;
                break;
            }
            break;
        case ID_BUTTON_SAVE:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                state = 13;
                break;
            }
            break;
        case ID_BUTTON_PERIOD:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                WM_SetCallback(period_button, period_button_on);
                WM_SetCallback(start_button, start_button_off);
                WM_SetCallback(stop_button, stop_button_off);
                WM_SetCallback(temp_button, temp_button_off);
                WM_MoveTo(upButton, 45,125);
                WM_MoveTo(dnButton, 45,174);
                break;
            }
            break;
        case ID_BUTTON_START:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                WM_SetCallback(period_button, period_button_off);
                WM_SetCallback(start_button, start_button_on);
                WM_SetCallback(stop_button, stop_button_off);
                WM_SetCallback(temp_button, temp_button_off);
                WM_MoveTo(upButton, 152,125);
                WM_MoveTo(dnButton, 152,174);
                break;
            }
            break;
        case ID_BUTTON_STOP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                WM_SetCallback(period_button, period_button_off);
                WM_SetCallback(start_button, start_button_off);
                WM_SetCallback(stop_button, stop_button_on);
                WM_SetCallback(temp_button, temp_button_off);
                WM_MoveTo(upButton, 269,125);
                WM_MoveTo(dnButton, 269,174);
                break;
            }
            break;
        case ID_BUTTON_TEMPURATURE:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                WM_SetCallback(period_button, period_button_off);
                WM_SetCallback(start_button, start_button_off);
                WM_SetCallback(stop_button, stop_button_off);
                WM_SetCallback(temp_button, temp_button_on);
                WM_MoveTo(upButton, 376,125);
                WM_MoveTo(dnButton, 376,174);
                break;
            }
            break;
        case ID_BUTTON_UP:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        case ID_BUTTON_DN:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateVacation(void);
WM_HWIN CreateVacation(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
